apiVersion: v1
kind: Service
metadata:
  name: form-submission-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: form-submission-app
